scrape_configs:

- job_name: env-metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - cadvisor:8080
    - nodeexporter:9100
    labels:
      host: prod-service
  - targets:
    - 192.168.80.203:7301
    - 192.168.80.203:7302
    labels:
      host: infonot-prod-facade
      
- job_name: proxy-metrics
  scrape_interval: 5s
  static_configs:
  - targets:
    - 192.168.80.203:8101
    labels:
      role: apigate
